services:
  postgres:
    image: postgres:15-alpine
    container_name: solvik_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: solvik_saas
      POSTGRES_USER: solvik_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-solvik_secure_password_2024}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
    ports:
      - "5432:5432"
    networks:
      - solvik_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "solvik_user", "-d", "solvik_saas"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: .
    container_name: solvik_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://solvik_user:${POSTGRES_PASSWORD:-solvik_secure_password_2024}@postgres:5432/solvik_saas
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - solvik_network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
    driver: local

networks:
  solvik_network:
    driver: bridge