version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: solvik_backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "npm install cors express && node simple-server.js"
    environment:
      - NODE_ENV=development
      - PORT=8000
    networks:
      - solvik_network

networks:
  solvik_network:
    driver: bridge